# Generated by Django 2.0.2 on 2018-02-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumption',
            old_name='meassure_time',
            new_name='measure_time',
        ),
        migrations.AlterField(
            model_name='device',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
